title: Jie Cui's Homepage
page-top-title: Jie Cui
top-section-bg-text: Computer Science
home-subtitle: Jie Cui&ensp;|&ensp;崔杰 | Professor, School of Computer Science and Technology 
copyright-text: '&copy; Jie Cui 2023-2024. All Rights Reserved.'
